.github/workflows/update-tailwind.yml
Tailwind CSS updates pretty often & it'll be really annoying to manually update the `app/assets/stylesheets/tailwind.css` file.
This adds a GitHub action which runs at 3am GMT every day which builds the latest version of the `tailwind.css` file then commits it back to the `main` branch.
Potentially you could also add a tag or something, then automate the release to RubyGems :D
=> Automate the updating of Tailwind CSS via GitHub Action

README.md
The install task [adds a `stylesheet_link_tag`](https://github.com/rails/tailwindcss-rails/blob/main/lib/install/tailwindcss.rb#L5) into `application.html.erb`
=> Fix helper typo in readme

lib/install/tailwindcss_with_webpacker.rb
Fixes the indentation of `require('postcss-import')` to match the rest of the required plugins.
=> Fix indentation of postcss-import require

lib/install/tailwindcss_with_webpacker.rb
The way it was before my change added an unexpected tab character and started the "require" at the wrong indentation level.
```
plugins: [
require('tailwindcss'),
require('postcss-import'),
```
vs:
```
plugins: [
require('tailwindcss'),
require('postcss-import'),
```
=> Fix indentation for require in postcss.config.js

README.md
- stylsheet -> stylesheet
- relased -> released
=> Fixes typos in the readme

lib/install/tailwindcss_with_webpacker.rb
Current webpacker install, was problematic.
Main issue is that current release of webpacker uses Postcss7.
Tailwind 2 expects Postcss8, and that causes a lot of issues.
Tailwind team has published Tailwind 2 compatible Postcss7 [package](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build)
So in order for the generator to work with Rails 6.1 defaults, this PR
deferes to use `tailwindcss@npm:@tailwindcss/postcss7-compat` package.
By, using this package users don't loose anything it is Tailwind 2.
--------------
There is a way to make it work without using the `Postcss7` package by
using latest `rails-webpacker` beta, but I think it is smarter for now
not to use beta releases.
When rails wepbacker publishes latest with `Postcss8` then we can change
the generator.
Shout …
=> FIX: Webpacker install

lib/tailwindcss/purger.rb, test/fixtures/simple.html.erb, test/purger_test.rb
Previously, decimal spacing classes such as `p-0.5` were incorrectly purged out. This PR fixes this by improving the class detection regex.
More details on the issue:
- The problem were utility classes that include a period, such as `px-0.5` or `gap-2.5`
- Such classes were correctly extracted from ERB, but incorrectly parsed out from the tailwind CSS file
- Because of the leading backslash required in CSS, e.g. the `.px-1\.5` class was extracted as `px-1` and it's fate was then decided by the purger as such :-)
Not sure if there was any particular reason for handling the period in the previous form of the regex, but this simple change has been working well for me so far.
Thanks for building such an awesome library, removing Webpack was a pleasure!
=> Correctly purge decimal spacing classes

lib/install/tailwindcss_with_webpacker.rb
During webpack installation generate `tailwind.config.js`.
This commit places that file inside `stylesheets/` dir, and link to it
inside `postcss.config.js`.
This is the blank Tailwind confg file that one can extend
to bring its own esthetics.
=> Webpacker: Add tailwind.config.js

lib/tailwindcss/purger.rb, test/purger_test.rb
This rewrite accomplishes a few things:
* Fixes #20.  Closes #22.
* Purges selectors that aren't on the same line as their block brace:
**Before**
```css
.sm\:aspect-w-1,
/* ... */
.sm\:aspect-w-15 > *,
@media (prefers-color-scheme: dark) {
}
```
* Purges empty "at rule" blocks (e.g. empty `@media` blocks).
* Purges comments, except within property values.
* Adds support for nested selector blocks, to prepare for the future.  For example, Tailwind has many `.group:hover .group-hover\:X` rules that could be written as `.group:hover { .group-hover\:X { ... } }`.
* Improves performance:
**Before**
```bash
$ bin/test -n test_basic_purge
Finished in 2.307380s, 0.4334 runs/s, 3.0337 assertions/s.
1 runs, 7 assertions, 0 failures, 0 errors, 0 skips
```
**After**
```bash
$ bin/test -n …
```
=> Rewrite Purger

.github/workflows/update-tailwind.yml
`tailwindcss-cli build` chokes on `require('tailwindcss/defaultTheme')` in `tailwind.config.js` added by 53089c1e1fb2f0ae232621a057320338436efa33.  Example failure: https://github.com/rails/tailwindcss-rails/runs/1725407564.
`tailwind build`, which is invoked by `yarn build`, handles this properly.  Running `yarn upgrade tailwindcss` beforehand ensures that the `tailwind build` command is installed, and updates the Tailwind version in `yarn.lock` to match the built `tailwind.css`.
---
Example success after this change: https://github.com/jonathanhefner/tailwindcss-rails/runs/1954932857.  Resulting commit: https://github.com/jonathanhefner/tailwindcss-rails/commit/9dd13676ba95982b914c13a6d3ad7de2b4688fa1.
=> Fix "Update Tailwind" action

README.md, lib/install/tailwindcss.rb
This stylesheet will interfere with Tailwind's reset of base styles.
=> Remove scaffolds styles on install

lib/tailwindcss/purger.rb, test/fixtures/placeholders.html.haml, test/fixtures/placeholders.html.slim, test/fixtures/show.html.haml, test/fixtures/show.html.slim, test/fixtures/simple.html.haml, test/fixtures/simple.html.slim, test/purger_test.rb
This PR changes the CLASS_NAME_PATTERN to work for haml templates.
Since haml syntax uses dots to chain class names, I first removed the dot from the search pattern...
But, to make sure it still works for decimal spacing classes (e.g. `my-1.5`), I added a pattern to allow dots which are preceded by a number between 0-3 and followed by a 5.
By looking through the tailwind documentation, I think all the different class patterns are covered by a test already, so I'm not sure how to improve the test coverage... I'm happy to add more tests, but would need some input first, on what to test for...
=> Change CLASS_NAME_PATTERN to work also for haml templates

README.md
I've ported "old" webpacker behaviour from this gem for the folks who
are using webpacker.
This PR just adds mention to the port in the docs.
=> Doc: Mention webpacker port

lib/install/tailwindcss.rb
Prior to this change, installing the engine via `bin/rails
tailwindcss:install` yielded the following diff:
```diff
--- a/app/views/layouts/application.html.erb
+++ b/app/views/layouts/application.html.erb
@@ -6,7 +6,9 @@
<%= csp_meta_tag %>
-    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
+
+    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
+    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>
</head>
```
After this change, the calls to `stylesheet_link_tag` with
`"inter-font"`, `"tailwind"`, and `"application"` all occur on their own
lines.
=> Generate `stylesheet_link_tag` on separate lines

.github/workflows/update-tailwind.yml
Follow-up to #48.
This prevents commits that only update `yarn.lock`, such as 2338bd6187da1f588903b2ba2f1d2692a654d6a3.
=> Commit auto-updates only if assets have changed

README.md
The Tailwind version is updated in b16e0c28e216c9131785d48c6bce6643f01f5633 by a Github Action.
This commit updates the Readme accordingly.
=> Update TW version in Readme after recent update

lib/generators/tailwindcss/controller/controller_generator.rb, lib/generators/tailwindcss/controller/templates/view.html.erb.tt, test/lib/generators/tailwindcss/controller_generator_test.rb, test/lib/generators/tailwindcss/scaffold_generator_test.rb
This PR fixes error on the controller generation:
`bin/rails g controller Home index`
Since, I'd to override rails scaffold controller to work with rails 6, I
needed to configure rails controller generator also.
=> FIX: Error when generating a controller.

Gemfile, Gemfile.lock
The test suite was failing with:
```
/home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require': cannot load such file -- rails/generators/mailer/mailer_generator (LoadError)
from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
from /home/runner/work/tailwindcss-rails/tailwindcss-rails/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
from …
```
=> Add actionmailer test dependency to fix test suite

lib/generators/tailwindcss/controller/templates/view.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/index.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/new.html.erb.tt
Signed-off-by: Marcus Heng <marcushwz@gmail.com>
There are redundant class names for font-size in some of the default generators. This is what get generated when I do:
```bash
rails g controller static_pages home
```
In this PR, I have removed the `text-lg` from the affected generators. The comparison of `text-lg` and `text-4xl` are as follow:
- `text-4xl`
- `text-lg`
=> Remove redundant font-size class from generators

README.md
Minor follow-up to fix a typo from ef3b98dc0b6083e53b61daaac4745a83f1b30659
=> Remove extra conjunction in README

.github/workflows/gem-install.yml, exe/tailwindcss, lib/tailwindcss-rails.rb, lib/tailwindcss/upstream.rb, rakelib/package.rake, tailwindcss-rails.gemspec
See #101 and comments in #96 to see some problems users are having where either:
- the `ruby` platform (vanilla) gem is installed and so `tailwindcss` is simply not found in the user's path
- bundler's lockfile needs to be updated with the current platform
This PR introduces two changes:
- upstream tailwindcss metadata are moved from the rakefile into lib/tailwindcss/upstream.rb for use by the gem
- the `exe/tailwindcss` script is always shipped with the gem
An job is added to the gem-install actions pipeline to test the scenario where a bundler lockfile needs to have the native platform added.
The net result is that when someone has the "ruby" platform vanilla gem installed because their platform is not supported, they will see this error message when they run "tailwindcss":
``` text …
```
=> error messages on unsupported platforms or when bundler platforms aren't correct

lib/install/tailwind.config.js
The dark mode feature  is now enabled by default.
[Source](https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration)
=> Remove setting the `dark-mode` explicitly

exe/tailwindcss
On darwin this means the error messages and bundler instructions will
name "x86_64-darwin". This makes the bundler lock file as general as
possible.
Previously the platform name included the OS version,
e.g. "x86_64-darwin-21", which was unnecessarily specific for this gem.
=> fix: name the platform using just architecture and os

lib/tailwindcss/upstream.rb, rakelib/package.rake
In this pull request: https://github.com/tailwindlabs/tailwindcss/pull/6693 I am adding linux-arm64 support to the tailwind standalone-cli.
This pull request adds linux-arm64 as a supported platform. It should only be merged after the pull request above has been merged.
=> Add tailwindcss-linux-arm64 support (make docker on Apple Silicon M1 workflow possible)

lib/install/tailwindcss.rb
Insertion point of the centering container was problematic.
Meaning, if someone has a `yield :somethig`
inside theirs `application.html.erb` old regex would pick that as a
insertion point and possiblly break the html structure.
This commit makes that regex more rigid to only insert centering
container around the `<%= yield %>`.
Fixes: https://github.com/rails/tailwindcss-rails/issues/98
=> Fix: Insert centring container around the yield

lib/tasks/build.rake
This PR adds a description to the watch rake tasks, to make it discoverable
When starting with a fresh Rails 7 app with the tailwind option, one can get easily get confused why updates to your html do not use an rebuilt tailwind.css file  (I sure was). While using `bin/dev` might be the new canonical, preferred way, it still would be helpful to make the watch task more discoverable. I was looking for it, with `rails -T` but the task `rails tailwindcss:watch` is hidden because it has no description.
=> add description to watch task

exe/tailwindcss
Not sure the ideal wording here, but after going on the journey recorded for all posterity in https://github.com/rails/tailwindcss-rails/issues/121, I thought maybe it would make sense to add some instructions to avoid someone else suffering the same fate in the future.
=> Add additional recovery step when running into platform related issues.

lib/tailwindcss/upstream.rb
- Temporarily move postcss to dependencies ([#7424](https://github.com/tailwindlabs/tailwindcss/pull/7424))
- Move prettier plugin to dev dependencies ([#7418](https://github.com/tailwindlabs/tailwindcss/pull/7418))
- Expose `context.sortClassList(classes)` ([#7412](https://github.com/tailwindlabs/tailwindcss/pull/7412))
- Fix preflight border color fallback ([#7288](https://github.com/tailwindlabs/tailwindcss/pull/7288))
- Correctly parse shadow lengths without a leading zero ([#7289](https://github.com/tailwindlabs/tailwindcss/pull/7289))
- Don't crash when scanning extremely long class candidates ([#7331](https://github.com/tailwindlabs/tailwindcss/pull/7331))
- Use less hacky fix for URLs detected as custom properties ([#7275](https://github.com/tailwindlabs/tailwindcss/pull/7275))
- …
=> Update tailwindcss to v3.0.22

README.md
I just copied this note from https://github.com/rails/jsbundling-rails
=> Docs: Add a note about building for testing

lib/install/tailwindcss.rb
This addresses and closes #139.
Currently, the installer adds a `<main>` element around `<%= yield %>` in `application.html.erb`. This is ok for new projects, but it's annoying for projects that add this gem later on since they likely already have changed their `application.html.erb` and installing the gem breaks the layout.
This proposed change first checks if `application.html.erb` looks standard around `<%= yield %>`, and only in that case wraps it in a `<main>` element.
=> Installer: don't add main in existing projects

README.md
While running `bin/rails tailwindcss:watch` from within a `Procfile`, it was noticed that the command returns an exit 0 status if this is happening from within a Docker container.
See https://github.com/tailwindlabs/tailwindcss/issues/5324 for same problem and solution.
This may present as a gotcha for those running their Rails app from `docker-compose.yml`. Suggestion here to add this useful piece of information in the README.
=> Docs: Add notes for running tailwindcss:watch in Docker

lib/tailwindcss/upstream.rb
- Fix extraction of multi-word utilities with arbitrary values and quotes ([#8604](https://github.com/tailwindlabs/tailwindcss/pull/8604))
- Fix casing of import of `corePluginList` type definition ([#8587](https://github.com/tailwindlabs/tailwindcss/pull/8587))
- Ignore PostCSS nodes returned by `addVariant` ([#8608](https://github.com/tailwindlabs/tailwindcss/pull/8608))
- Fix missing spaces around arithmetic operators ([#8615](https://github.com/tailwindlabs/tailwindcss/pull/8615))
- Detect alpha value in CSS `theme()` function when using quotes ([#8625](https://github.com/tailwindlabs/tailwindcss/pull/8625))
- Fix "Maximum call stack size exceeded" bug ([#8636](https://github.com/tailwindlabs/tailwindcss/pull/8636))
- Allow functions returning parallel variants to mutate the container …
=> Update to Tailwind CSS v3.1.3

lib/install/tailwind.config.js
Add the `public/*.html` path to tailwind content config:
- It's pretty standard to have to customize the style of the default
Rails 404, 422 and 500 page.
This PR adds the path to those files to be able to style them with
tailwind.
=> Add the `public/*.html` path to tailwind content config:

README.md
The version of the gem (2.0.8) made me think it was using Tailwind v2. I included the specific version so that it's clear that this gem is using Tailwind CSS v3.0 (and is not to be confused with using CSS 3).
=> Indicate explicit Tailwind CSS version in README

.github/workflows/gem-install.yml, Gemfile.lock, README.md, lib/tailwindcss/upstream.rb, rakelib/package.rake
Windows support note: we ship the same executable in two gems, the `x64-mingw32` and `x64-mingw-ucrt` flavors because Ruby < 3.1 uses the MSCVRT runtime libraries, and Ruby >= 3.1 uses the UCRT runtime libraries.
You can read more about this change here:
> https://rubyinstaller.org/2021/12/31/rubyinstaller-3.1.0-1-released.html
Closes #172
=> support x64-mingw-ucrt for Ruby 3.1 users (#172)

lib/tasks/build.rake
We are encountering issues where our CI pipeline can succeed without successfully building Tailwind. It appears this is possible because the `TAILWIND_COMPILE_COMMAND` is run with `system` and the return code is never checked. When problems occur, an error is printed to the console but the return code from running `rails tailwindcss:build` is still `0`.
Build errors, such as those caused by a version mismatch between the `tailwindcss-rails` and the corresponding binary gem, could cause a CI build to fail silently and lead to an unstyled site in production. Therefore I believe it is essential that these rake tasks pass through the return code.
Using `Kernel#exec` replaces the current process by running the given external command, thereby passing through any return codes. If this is …
=> use exec to run tailwind binary, so return codes pass through

lib/tailwindcss/upstream.rb
I need the fix in https://github.com/tailwindlabs/tailwindcss/pull/8687 which was released in v3.1.4.
Has there been any thought in decoupling `tailwindcss-rails` releases from Tailwind? It would be nice to be able to use the latest Tailwind release without having to wait for `tailwindcss-rails` to be released.
=> Update to Tailwind CSS v3.1.8

lib/tasks/build.rake
This is a followup to https://github.com/rails/tailwindcss-rails/pull/181
After upgrading one of our repos to `2.0.11`, we unfortunately learned that running commands with `Kernel#exec` instead of `Kernel#system` introduces a failure in the `assets:precompile` pipeline. Due to `exec` hijacking the process from Ruby, subsequent steps will not run after the tailwind build completes.
This will probably need to be treated as an urgent bugfix as it may result in a failure of the asset pipeline to output images, javascript, etc.
This change effectively reverts #181, and adds the `exception: true` flag which will allow `#system` to raise when encountering failure codes.
=> address issue when running commands with #exec

.github/workflows/ci.yml, .github/workflows/gem-install.yml
- cancel builds in progress for a ref if another commit is pushed
- avoid multiple duplicate builds on pull request pushes
- allow workflow dispatch in a pinch
=> ci: better pipeline config

.github/workflows/ci.yml, exe/tailwindcss, lib/tailwindcss-rails.rb, lib/tailwindcss/commands.rb, lib/tasks/build.rake, test/integration/user_journey_test.sh, test/lib/tailwindcss/commands_test.rb
This PR introduces CI pipeline test coverage for our documented user journey, which will exercise the rake tasks. It also closes #184.
After the first commit, we [see the expected failure](https://github.com/rails/tailwindcss-rails/runs/8170487679?check_suite_focus=true#step:4:357) for #184:
```
Specified input file D:/a/tailwindcss-rails/tailwindcss-rails/Has\ does not exist.
```
Note that this is a pretty heavy refactoring, where code is being moved
from `exe/tailwindcss` to `lib/tailwindcss/commands.rb` where we can
more easily run unit tests on it.
Note also that we no longer use Shellwords to build command strings, a
library which does not generate correct strings on Windows
platforms. Instead we consistently use arrays of command arguments,
which can be passed to `exec` or `system` …
=> rake task execution: test coverage and refactoring

CHANGELOG.md, README.md, lib/tailwindcss/commands.rb, lib/tasks/build.rake, test/lib/tailwindcss/commands_test.rb
Suggested by #163, this PR implements a debug "option" via rake task parameters.
Users can run `rails tailwindcss:build[debug]` or `rails tailwindcss:watch[debug]` to generate unminified assets.
=> feat: generate unminified assets with `debug` task param

CHANGELOG.md, README.md, lib/tailwindcss/commands.rb, lib/tasks/build.rake, test/lib/tailwindcss/commands_test.rb
Polling was added upstream in 3.1.0 to solve timing issues with systems that don't fully support file system events (see https://github.com/tailwindlabs/tailwindcss/pull/7725).
This builds on the commits at #198 to support a `poll` argument to the `tailwindcss:watch` rake task:
```
rails tailwindcss:watch[poll]
```
Because we're using rake task arguments, we can combine `poll` with the `debug` argument from #198 like so:
```
rails tailwindcss:watch[debug,poll]
```
This PR supersedes #168
=> feat: support polling for watching files

.github/workflows/ci.yml, .github/workflows/gem-install.yml, lib/tailwindcss/commands.rb
Upstream issue is https://github.com/rubygems/rubygems/issues/5938
This PR adds tests coverage, updates CI pipelines, and explicitly casts the platform string as a Gem::Platform to work around the rubygems issue.
Closes #200
=> ci: try to reproduce the musl issue from #200

CHANGELOG.md, lib/tailwindcss/upstream.rb
I've not been able to test this, but I believe this is the correct way to update (looking at: https://github.com/rails/tailwindcss-rails/pull/186/files)
=> Update tailwind to version 3.2

.github/workflows/ci.yml, .github/workflows/gem-install.yml
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12
=> ci: update actions

Gemfile, Gemfile.lock
The need for sqlite3 was removed in 6f275f0.
Adding the same native platforms as `rails/rails`.
=> dev: remove sqlite3 and add native platforms to the Gemfile.lock

lib/install/dev
In a similar manner to https://github.com/rails/dartsass-rails/pull/35.
This Pull Request streamlines the content of the `bin/dev` script across `rails/tailwindcss-rails`, `rails/dartsass-rails`, `rails/jsbundling-rails` and `rails/cssbundling-rails` so you don't run into conflicts when running multiple installers:
```
❯ rails tailwindcss:install
Add Tailwindcss include tags and container element in application layout
insert  app/views/layouts/application.html.erb
Build into app/assets/builds
exist  app/assets/builds
identical  app/assets/builds/.keep
append  Procfile.dev
Add bin/dev to start foreman
conflict  bin/dev
Overwrite /Users/marcoroth/Development/project/bin/dev? (enter "h" for help) [Ynaqdhm]
```
This PR applies the changes from …
=> Unify `bin/dev` script with other js/css installers

lib/tailwindcss/upstream.rb
This update, among other things, fixes a bug with using "raw" content in the tailwind config (https://github.com/tailwindlabs/tailwindcss/pull/9773) which I use through this gem to output tailwind styles for user supplied markup.
Full release notes: https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.2.3
=> Update upstream tailwindcss version 3.2.2 -> 3.2.3

README.md
The current docs are a bit confusing, because only `rake` tasks get enhanced by this library, but there's also `rails` tasks that look the same.
I tried to make it a bit more clear.
Disclaimer: it's possible I've gotten confused and there's a much simpler recommended approach... I'd love for that to be true!
=> Clarify how to run Tailwind command in CI

lib/tasks/build.rake
By default, removes the verbose log line when running a Tailwind build. This isn't really needed most of the time. You can use the `verbose` option to include it.
```
% bin/rake "tailwindcss:build[verbose]"
["/Users/alex/.rvm/gems/ruby-3.1.2/gems/tailwindcss-rails-2.0.21-x86_64-darwin/exe/x86_64-darwin/tailwindcss", "-i", "/Users/alex/Code/foo/app/assets/stylesheets/application.tailwind.css", "-o", "/Users/alex/Code/foo/app/assets/builds/tailwind.css", "-c", "/Users/alex/Code/foo/config/tailwind.config.js", "--minify"]
Rebuilding...
Done in 480ms.
% bin/rake tailwindcss:build
Rebuilding...
Done in 500ms.
```
=> `verbose` arg for build commands

lib/generators/tailwindcss/scaffold/scaffold_generator.rb, lib/generators/tailwindcss/scaffold/templates/partial.html.erb.tt, test/lib/generators/tailwindcss/scaffold_generator_test.rb
This PR fixes error when generating nested models such as:
`bin/rails g scaffold admin/role name description`
Closes #227
=> Fix generating nested models

lib/tailwindcss/commands.rb, lib/tasks/build.rake, test/lib/tailwindcss/commands_test.rb
Looking for feedback on this approach.
This will avoid double-compression which breaks styles.
Fixes #243
See https://github.com/rails/rails/issues/47553
=> feat: tailwind will not minify when Rails CSS compression is on

lib/install/tailwind.config.js
Tailwind has 5 official plugins but only the first 3 are installed by default. 
This pull request adds the final 2 plugins (line clamp and container queries) to the installer for config/tailwind.config.js.
=> Added 2 official Tailwind plugins

lib/install/tailwind.config.js, lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.3.0
The line-clamp plugin is now baked into the framework itself: https://tailwindcss.com/blog/tailwindcss-v3-3
=> Update tailwindcss to v3.3.0

CHANGELOG.md, README.md, lib/tailwindcss/commands.rb, test/lib/tailwindcss/commands_test.rb
If a user has installed the `ruby` platform gem, but has the `tailwindcss` executable installed in their path, then we should fall back to that.
Closes #224
=> feat: fall back to locally-installed tailwindcss executables

lib/tailwindcss/commands.rb, lib/tasks/build.rake, test/lib/tailwindcss/commands_test.rb
Passes `-w always` along to tailwindcss, which keeps the watch going even if stdin closes (https://github.com/tailwindlabs/tailwindcss/pull/9966).
=> Handle `tailwindcss:watch[always]`

lib/tasks/build.rake
jsbundling-rails (https://github.com/rails/jsbundling-rails/pull/128) and cssbundling-rails (https://github.com/rails/cssbundling-rails/pull/116) do the same and it's useful for people who are using RSpec.
=> Enhance spec:prepare command with tailwindcss:build command

CHANGELOG.md, lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.3.3
=> dep: update tailwindcss to v3.3.3

README.md
Now that https://github.com/rails/rails/pull/46664 is merged, we can simplify the testing instructions.
Technically these instructions aren't true until Rails 7.1, so I'm happy to leave the PR open until then if that's preferred.
=> Simplify "Building for testing" [merge after Rails 7.1]

CHANGELOG.md, lib/install/Procfile.dev
This commit adds the `--open` option so a remote session can be started using `rdbg --attach`. This allows to debug inside a foreman process.
This will replicate what we have on jsbundling-rails https://github.com/rails/jsbundling-rails/blob/main/lib/install/Procfile.dev#L1 and on cssbundling-rails https://github.com/rails/cssbundling-rails/blob/main/lib/install/Procfile_for_bun.dev#L1
=> Run the server with remote debugging enabled

lib/tailwindcss/commands.rb, test/lib/tailwindcss/commands_test.rb
Running Ruby 3.3.0-preview2 and Ruby Gems 3.5.0.dev I am seeing the following deprecation warning:
```
NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4
Gem::Platform.match called from /Users/[me]/dev/tailwindcss-rails/lib/tailwindcss/commands.rb:37.
```
This patch replaces calls to `Gem::Platform#match` to `Gem::Platform#match_gem?` as recommended in [the source](https://github.com/rubygems/rubygems/blob/28f813ba97d6ed3a8ede427b0dc5e7fab47aa02f/lib/rubygems/platform.rb#L27).
This update passes `nil` as the second argument to `match_gem?`. The implementation of `match_gem?` appears to ignore the second argument (`gem_name`) and it's actually identical to the deprecated `match` method:
```ruby
def …
```
=> Fix deprecation warnings in 3.5.0

CHANGELOG.md, lib/tailwindcss/upstream.rb
Update tailwindcss from 3.3.3 to 3.3.5
- https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.3.4
- https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.3.5
=> dep: tailwindcss 3.3.5 (from 3.3.3)

.github/workflows/ci.yml, tailwindcss-rails.gemspec, test/lib/tailwindcss/commands_test.rb
=> dep: rubygems >= 3.2.0 for Platform#match_gem?

.github/workflows/ci.yml, CHANGELOG.md, Gemfile.lock, lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.3.7
=> dep: bump tailwindcss to v3.3.7

CHANGELOG.md, README.md, lib/puma/plugin/tailwindcss.rb
This adds a puma plugin that runs watch mode only in development.
=> Add puma plugin

lib/install/Procfile.dev, lib/install/dev
Fixes #291
Lazily load the `debug` gem in order to mitigate issues with docker environments such as `dip`.
Backport the port configuration so it allows overriding.
=> Lazily load the debug gem

lib/generators/tailwindcss/scaffold/templates/_form.html.erb.tt
Fixes #304
Previously, form would render like:
With this PR, form renders like:
=> fix: password form field classes

README.md
Add a paragraph to the Troubleshooting section about resolving a misconfiguration that otherwise causes double-processing of Tailwind's entry file, as described in issue #190.
=> Add section about conflict with with asset pipeline

.github/workflows/ci.yml
because the scaffold generation changed in Rails 7
see @dixpac's comments at #308 for context
=> ci: add a job that tests against Rails 6.1

CHANGELOG.md, lib/generators/tailwindcss/controller/controller_generator.rb, lib/generators/tailwindcss/mailer/mailer_generator.rb, lib/generators/tailwindcss/scaffold/scaffold_generator.rb, test/lib/generators/tailwindcss/controller_generator_test.rb, test/lib/generators/tailwindcss/mailer_generator_test.rb, test/lib/generators/tailwindcss/scaffold_generator_test.rb, test/test_helper.rb
Originally reported at #164
I think this PR is preferable to #247 because it has tests and is a simpler fix.
Note that in order to test this, the test suite now uses the same temporary directory for all tests, so we are then able to set `Rails::Generators.templates_path` before the generator classes are instantiated.
cc @dixpac
=> Allow users to override scaffold generator templates

README.md, lib/tailwindcss/commands.rb, test/lib/tailwindcss/commands_test.rb
Allows loading a custom `postcss.config.js` if it exists in the `config` folder.
This allows for instance enabling nesting like so:
```
module.exports = {
plugins: {
'postcss-import': {},
'tailwindcss/nesting': {},
tailwindcss: {},
autoprefixer: {},
},
}
```
=> Allow custom postcss.config.js

.github/workflows/ci.yml, .github/workflows/gem-install.yml, .github/workflows/upstream.yml
GitHub is [planning to upgrade to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Versions prior to actions/checkout v3 use an outdated version of node, so we will upgrade to actions/checkout v4, where [Node 20 is the default](https://github.com/actions/checkout/releases/tag/v4.0.0).
=> Bump actions/checkout

lib/puma/plugin/tailwindcss.rb
`tailwindcss -w` reads stdin, probably to detect stdin close.
When using binding.irb or debugger with tailwindcss-rails, some keystrokes are taken by tailwindcss  and IRB/Debug can't read from stdin correctly. Keystroke disappears, and sometimes hangs up.
To not let tailwindcss watch command read stdin, we should use `IO.popen(command, 'r+')` instead of `system(*command)`.
Workaround for https://github.com/rails/tailwindcss-rails/discussions/346
```ruby
watch_command = ['./node_modules/.bin/tailwindcss', '-w']
Thread.new do # same for `fork do`
system(*watch_command)
puts 'command finished'
end
sleep 1
binding.irb
```
Before this pull request, Ctrl-D will stop `rails s`. Closing stdin will stop tailwind, then puma will stop with a message `Detected tailwind has gone away, stopping …
=> Avoid stdin read by tailwindcss watch command

.github/workflows/gem-install.yml
and pin x86_64-darwin to macos-13
See flavorjones/ruby-c-extensions-explained#30 for context
=> ci: add arm64-darwin coverage on macos-14

CHANGELOG.md, lib/install/tailwind.config.js
This plugin was originally a polyfill to handle the time gap until Safari 15 was released (in Fall 2021), and so is beyond its useful lifetime for anyone not targetting ancient browsers.
Closes #344
cc @searls
=> generator: drop the tailwind aspect-ratio plugin

CHANGELOG.md, lib/generators/tailwindcss/scaffold/templates/edit.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/index.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/partial.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/show.html.erb.tt
This updates the ERB template to be in sync with the template in rails/rails
Fixes #341.
=> generator: sync erb template

lib/generators/tailwindcss/scaffold/templates/_form.html.erb.tt
The contrast provided by the `border-gray-200` Tailwind utility class is very poor. It's nearly impossible to distinguish the edges  of an input field on a white background. 
That's not a great default experience for Rails scaffolds.
With a slight bump to `border-gray-400`, things are much easier  to distinguish.
Here's a simple example where I only changed the border class on the `Name` field at the top: 
Safari:
Firefox: 
Chrome: 
With a stock Rails 7.1 app, I genuinely could not distinguish the edges of any input field until I made this change. I think the examples speak for themselves. I can understand the desire for subtlety but I think this change would be beneficial. I'm deliberately not address a similar issue with non-call-to-action buttons in this PR, in case there's …
=> Increase form input field border contrast

Gemfile.lock
Should resolve https://github.com/rails/tailwindcss-rails/security/dependabot/52
=> dep: bundle update

lib/install/tailwindcss.rb
Ref: https://github.com/rails/rails/pull/52433.
Fixes `rails new myapp --main --css tailwind` currently blocking, waiting for user input:
```
Add bin/dev to start foreman
conflict    bin/dev
Overwrite /Users/jerome/c/rails/myapp/bin/dev? (enter "h" for help) [Ynaqdhm]
```
After merging this PR, it would be nice if a new release could be cut, so `rails new myapp --main --css tailwind` doesn't block.
=> Force bin/dev overwrite to deal with new default bin/dev file

lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.9
=> dep: bump tailwindcss to v3.4.9

lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.12
=> dep: bump tailwindcss to v3.4.12

.github/workflows/upstream.yml, lib/generators/tailwindcss/authentication/templates/views/passwords/edit.html.erb, lib/generators/tailwindcss/authentication/templates/views/passwords/new.html.erb, lib/generators/tailwindcss/authentication/templates/views/sessions/new.html.erb, test/integration/user_journey_test.sh
And add test coverage for the generator templates.
We can revert the "copy templates" commit once beta2 is out.
See https://github.com/rails/tailwindcss-rails/pull/407 for context.
=> Make copies of the auth templates for Rails 8 beta1

lib/generators/tailwindcss/scaffold/templates/_form.html.erb.tt
Followup to https://github.com/rails/tailwindcss-rails/pull/416
They got renamed (with aliases being present) in:
* https://github.com/rails/rails/pull/52432
* https://github.com/rails/rails/pull/52467
This ensures the correct classes are generated for both old and new versions. I added a test locally but it can only assert against the exact css classes since there is nothing else to properly distinquish them. I can add this here if you wish, just didn't seem like the best test.
@enderahmetyurt, I suspect you generated your sample app with rails 8.0.0.beta1 which is why it looked weird for you.
=> Handle both rails 7.2 and rails 8.0 field types for checkbox/textarea

.github/workflows/ci.yml, .github/workflows/upstream.yml, CHANGELOG.md, lib/tailwindcss/commands.rb, test/integration/user_journey_test.sh, test/lib/tailwindcss/commands_test.rb
Tailwind CSS v4 is a big overhaul in how tailwind detects CSS classes. Instead of specifying config and input files, the CLI scans the entire project directory.
More information on this change here: https://tailwindcss.com/blog/tailwindcss-v4-alpha
This PR updates the build and watch commands to skip the `-i` and `-c` parameters if the version of Tailwindcss::Ruby is v4.
This PR also adds matrixed (across Tailwind v3 and v4) unit test coverage for the base commands, and integration test coverage for the generated CSS file.
Known issue: this logic will break for users who are using the `TAILWINDCSS_INSTALL_DIR` feature of `tailwindcss-ruby` to run a different version of tailwindcss than declared by the gem. This PR hides that version check behind the `Commands.tailwindcss_version` method, …
=> Add experimental support for Tailwind CSS v4

lib/generators/tailwindcss/authentication/templates/app/views/passwords/edit.html.erb, lib/generators/tailwindcss/authentication/templates/app/views/passwords/new.html.erb, lib/generators/tailwindcss/authentication/templates/app/views/sessions/new.html.erb, lib/generators/tailwindcss/scaffold/templates/_form.html.erb.tt, lib/install/tailwind.config.js
Typography and container queries aren't used by this gem directly.
The form plugin is used, but I've attempted to complete styling of the generator template forms without it (though there may still be some differences due to the absence of style reset).
See #443 and #441 for examples of users getting poor rendering due to conflicts between Tailwind UI and the form plugin.
@dhh Really it's up to you whether this kind of minimalism is in line with your vision for the gem? It does seem like some developers and designers want to start from a vanilla initialization that matches what other tailwindcss tools do (Vite, CDN).
Some alternative approaches are also discussed in the comments in #443.
=> Drop default plugins "form", "typography", and "container-queries"

Gemfile.lock, lib/generators/tailwindcss/authentication/templates/app/views/passwords/edit.html.erb, lib/generators/tailwindcss/authentication/templates/app/views/passwords/new.html.erb, lib/generators/tailwindcss/authentication/templates/app/views/sessions/new.html.erb, lib/generators/tailwindcss/scaffold/templates/_form.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/edit.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/index.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/new.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/partial.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/show.html.erb.tt
I made a few modifications to the scaffold views. I'm attaching some images to showcase the before/after of these changes. The changes:
* remove the mx-auto to most of the views. It makes the scaffold weird as you have to re-focus your sight on every new page. Keep the w-2/3 so the content always starts in the same place.
* add titles to all pages (show page never had a title IIRC). I think this is nice to keep consistency.
* add content_for :title to all pages as it was only present in the index view
* add a hover state to buttons and links and adjust the padding
* add semantic colors to buttons (just the destroy one, made it red).
* add an empty state when the list has no items
* change the border/focus colors on errored fields
* improve the errors list
* fixed minor indentations and …
=> Improve scaffold views

CHANGELOG.md, README.md, lib/puma/plugin/tailwindcss.rb, lib/tailwindcss/commands.rb
that is, not in `rails server`.
Closes #458
=> feat: support running the puma plugin in a bare puma process

CHANGELOG.md, README.md
add upgrade notes to the README, and start a CHANGELOG entry
@EricGusmao and @excid3 I'd love your eyeballs on this if you have time.
=> doc: add upgrade notes to the README

.github/workflows/ci.yml, .github/workflows/upstream.yml, tailwindcss-rails.gemspec
Now that we've done the work to be compatible with Tailwind v4 in a v4.0.0.rc1, I think we know enough to recommend against using Tailwind v4 with tailwindcss-rails v3.
Let's prevent unintentional upgrades and problems for users. This will go into a (final?) v3 release.
=> dep: pin tailwindcss-ruby to `~> 3.0`

test/integration/user_install_test.sh, test/integration/user_upgrade_test.sh
so we can integration test from tailwindcss-ruby's downstream CI pipeline
=> test: restore the ability to inject tailwindcss-ruby bundler opts

lib/install/upgrade_tailwindcss.rb
In order to rebase other prs i opened i had to upgrade my local installation. Since i don't have npx installed, the task was aborted before the inter font was removed from the layout.
If for some reason (like in my case) you can't run the upgrade tool or it fails, you have to manually upgrade and also manually edit the layout to remove the inter font. This can be avoided if we remove it before running the npx upgrade tool.
other than that, it works great. 😄 . I tried upgrading manually and using the tool and in all cases works perfectly.
=> remove inter font before upgrading using the npx script

lib/install/install_tailwindcss.rb, lib/install/upgrade_tailwindcss.rb, test/integration/user_install_test.sh
In Rails 8, propshaft detects `:app` and loads all the css files under app/assets/stylesheets, so we may not need this explicit tag for tailwind.
On installation, omit the tailwind stylesheet link tag if `:app` is already being passed to stylesheet_link_tag in the layout.
On upgrade, remove the tailwind stylesheet link tag if `:app` is already being passed to stylesheet_link_tag in the layout.
See related discussion at https://github.com/rails/tailwindcss-rails/pull/412
=> fix: unnecessary stylesheet_link_tag for tailwind

README.md, lib/install/install_tailwindcss.rb, lib/install/upgrade_tailwindcss.rb, lib/tailwindcss/commands.rb, lib/tailwindcss/engine.rb, test/integration/user_install_test.sh, test/integration/user_upgrade_test.sh
This file should not be included in the stylesheet link tags served to user agents. But by default, Rails 8 apps add a tag for all CSS files under `app/assets` (courtesy of a Propshaft feature handling a source named `:all`), and so this file is being included unintentionally.
Going forward, in version 4.x of this gem (which pins to Tailwind v4), the installer will place the file into `app/assets/tailwind`. The upgrader will move it from `app/assets/stylesheets` to `app/assets/tailwind`.
And the gem's railtie adds `app/assets/tailwind` to `config.assets.excluded_paths` to make sure it doesn't get served up by the `stylesheet_link_tags :app` call in the application layout.
This is being tested with both Rails 7.2 (without Propshaft) and Rails 8 (with Propshaft) and it looks good.
Fixes …
=> Move application.tailwind.css to a dir ignored by propshaft

lib/generators/tailwindcss/authentication/authentication_generator.rb
If you run `rails g` you can see the following output under Tailwindcss:
```
Tailwindcss:
tailwindcss:authentication
```
You would normally run just `rails g authentication` and it will pick your template engine of choice (tailwindcss comes up as a template engine) and run that generator for you.
This PR hides it from the help text, similar to https://github.com/rails/rails/pull/53798 (does the same to `erb:authentication`).
=> Hide tailwindcss:authentication from rails g

README.md, tailwindcss-rails.gemspec
1. Clean up the README's upgrade docs.
@EricGusmao please take a look when you get a moment. 🙏
2. Add a post-install message pointing people to the upgrade guide:
```
== Upgrading to Tailwind CSS v4 ==
If you are upgrading to tailwindcss-rails 4.x, please read the upgrade guide at:
https://github.com/rails/tailwindcss-rails/blob/main/README.md#upgrading-your-application-from-tailwind-v3-to-v4
If you're not ready to upgrade yet, please pin to version 3 in your Gemfile:
gem "tailwindcss-rails", "~> 3.3.1"
```
=> Prep docs and post-install message for final v4.0.0 release

README.md
If an application has custom css files that use tailwind classes like this:
```css
/* app/assets/stylesheets/pagy.css */
@layer components {
.pagy.info {
@apply text-gray-600 ml-0 mt-1 text-sm;
}
}
```
referenced like this:
```css
/* app/assets/stylesheets/application.tailwind.css */
/* ... */
@import "pagy.css";
/* ... */
```
Then, the reference has to be changed to:
```css
/* app/assets/stylesheets/application.tailwind.css */
/* ... */
@import "../stylesheets/pagy.css";
/* ... */
```
for the upstream upgrade tool to run successfully
because the base tailwind css file will be changed
from `app/assets/stylesheets/application.tailwind.css`
to `app/assets/tailwind/application.css`
=> doc: Add to v3-v4 upgrade guide about custom css files

CHANGELOG.md, lib/generators/tailwindcss/authentication/templates/app/views/passwords/edit.html.erb, lib/generators/tailwindcss/authentication/templates/app/views/passwords/new.html.erb, lib/generators/tailwindcss/scaffold/templates/_form.html.erb.tt
=> show focus outlines

test/integration/user_install_test.sh, test/integration/user_upgrade_test.sh
In tailwindcss v4.0.5, tailwindlabs/tailwindcss#16211 is smarter about not including unused theme variables, but `static` is the documented way to opt into the older behavior.
=> test: update the integration install test to use static variable

README.md
Since the inter font is no longer packaged within this project, I think it doesn't make sense to add its license anymore.
=> Remove inter font license from the README as the font is no longer packaged

lib/generators/tailwindcss/scaffold/templates/partial.html.erb.tt
The partial used `<p>` elements for each attribute, which auto-close if it contains a `<div>` element (see [the technical summary of the p tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p#technical_summary)). To avoid this, I'm changing the `p` elements to `div` elements.
Also, adding some basic styling for the attachment links.
See before and after screenshots:
| before | after | comment |
| --- | --- | --- |
| ![image](https://github.com/user-attachments/assets/a64521c5-ab98-4829-95c2-d8ea3ea0d5e9) | ![image](https://github.com/user-attachments/assets/de6a6a2a-363e-4c7a-a11c-eca27966a8b8) | the space between "Documents" and the links changed due to the correct use of tags, and the links now are styled differently (similar to "forgot your password?" link |
| …
=> improve partial: correct use of tags + attachment links styling

lib/generators/tailwindcss/scaffold/templates/index.html.erb.tt, test/integration/user_install_test.sh
between objects.
Currently, when your collection has many objects, and given the "show this xxx" button is grey, it's hard to distinguish when an object ends and another one begins. 
This PR adds a subtle division between objects and wraps the partial in a flex item, moving the show button to the right hand side. Also, as suggested in #457 , I've added the edit and destroy buttons.
| before | after |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/024de0b2-72c9-4379-ba93-e812d9f63ab4) | ![image](https://github.com/user-attachments/assets/e10a908f-e001-4179-b0ac-495321d88bd8) |
=> index: show the actions to the right of the partial and add a division

lib/generators/tailwindcss/scaffold/templates/index.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/show.html.erb.tt
In the past, the scaffold generator added a confirm prompt to the destroy button. This PR adds it back only if Turbo is available.
=> Add confirm prompt if turbo is available

README.md
Updated readme to explain how to install plugins.
Discussion: https://github.com/rails/tailwindcss-rails/issues/502#issuecomment-2671620275
cc @flavorjones
=> Explain plugins in readme

README.md, lib/tailwindcss/commands.rb, test/lib/tailwindcss/commands_test.rb
Hi, this PR adds an environment variable to generate non-minified assets as discussed in #400
=> Tailwindcss debug environment variable

lib/generators/tailwindcss/authentication/templates/app/views/passwords/edit.html.erb, lib/generators/tailwindcss/authentication/templates/app/views/passwords/new.html.erb, lib/generators/tailwindcss/authentication/templates/app/views/sessions/new.html.erb, lib/generators/tailwindcss/scaffold/templates/_form.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/edit.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/index.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/new.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/partial.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/show.html.erb.tt
As always, here's the before/after:
| before | after |
| --- | --- |
| ![sessions_new](https://github.com/user-attachments/assets/3009e332-9faa-4e7b-a7e7-2b03cea6c9f6) | ![sessions_new](https://github.com/user-attachments/assets/a45295a4-8d15-4ec6-bb12-54dcde235c0b) |
| ![passwords_new](https://github.com/user-attachments/assets/c44c04df-5df0-43ee-bbff-48fd412e996b) | ![passwords_new](https://github.com/user-attachments/assets/9dd9bea1-87bb-4b1f-a8c6-df6529239563) |
| ![passwords_edit](https://github.com/user-attachments/assets/cecd246c-e8e7-41df-9807-01fa1cb427f0) | ![passwords_edit](https://github.com/user-attachments/assets/9fa9f436-434b-4e9c-88d1-e79971cb463c) |
| ![index](https://github.com/user-attachments/assets/114cf14f-4956-4c8a-87ed-e8181b658476) | …
=> Improve views for mobile devices

README.md, lib/install/upgrade_tailwindcss.rb
The upgrade tests started failing in CI with this error from the tailwind upgrade tool:
│ Migrating templates…
TypeError: Cannot read properties of undefined (reading 'flatMap')
at ca (file:///home/runner/.npm/_npx/0044b4041b3b52e1/node_modules/@tailwindcss/upgrade/dist/index.mjs:229:5661)
The upgrade tool failed!
You probably need to update your configuration. Please read the error messages,
and check the Tailwind CSS upgrade guide at https://tailwindcss.com/docs/upgrade-guide.
and it seems like updating to the latest version of the upgrade tool fixes it.
=> ci: use the latest @tailwindcss/upgrade package

lib/generators/tailwindcss/scaffold/templates/index.html.erb.tt, lib/generators/tailwindcss/scaffold/templates/show.html.erb.tt
Removed two unneeded div wrappers. The one in index isn't needed because its parent is `flex`, the one in show can be avoided by adding `form_class` to the button_to. It generates cleaner partials an easier to change.
=> Simplify markup

README.md, lib/tailwindcss/commands.rb, lib/tasks/build.rake
- The "verbose" flag turns on additional debugging output from tailwindcss
- Document the "watchman" problem
- Document how to use the "verbose" flag when troubleshooting
=> Improve the state of debugging when things go wrong

README.md, lib/install/upgrade_tailwindcss.rb
We're pinning to v4.1.4 because v4.1.5 of the upgrade tool [introduces a dependency version check on tailwind](https://github.com/tailwindlabs/tailwindcss/pull/17717) and I haven't been able to figure out how to get that to work reliably and I am extremely frustrated with the whole thing.
The error we're seeing in CI and in development with v4.1.5:
```
run    npx @tailwindcss/upgrade --force --config /home/flavorjones/code/oss/tailwindcss-rails/My\ Workspace/test-upgrade/config/tailwind.config.js from "."
≈ tailwindcss v4.1.5
│ Searching for CSS files in the current directory and its subdirectories…
Error: Tailwind CSS is not installed
at k.factory (file:///home/flavorjones/.local/share/mise/installs/node/22.12.0/lib/node_modules/@tailwindcss/upgrade/dist/index.mjs:194:727)
at k.get …
```
=> Pin the npm upgrade task to @tailwindcss/upgrade@4.1.4

.github/workflows/ci.yml, test/integration/user_install_test.sh, test/integration/user_upgrade_test.sh
- Rails 7.2 upstream build was failing because rack 3 came out and the Rails 8 dependencies are no longer compatible with Rails 7.2
- Rails 8.0 upstream build was failing because bundler no long installs a binstub for itself, so bcrypt was not being installed
=> ci: Get green (August 2025 edition)
