rails/tailwindcss-rails

lib/generators/tailwindcss/controller/templates/view.html.erb.tt
The generated view for the controller was missing a closing </div>
=> Close DIV generated for controller view

README.md
Documenting some common problems and the workarounds/fixes.
=> doc: update README with a troubleshooting section

lib/install/Procfile.dev, lib/install/tailwindcss.rb
fix execute path `rails tailwindcss:watch` for Profile.dev
```
$ foreman start -f Procfile.dev css
08:46:00 css.1  | unknown command: rails tailwindcss:watch
```
=> fix exec path for Procfile.dev

test/integration/user_journey_test.sh
for integration testing
see https://github.com/rubygems/rubygems/pull/5897
=> ci: use `bundle add` with the new `--path` param

.github/workflows/gem-install.yml, lib/tailwindcss/upstream.rb
Add support for arm-linux and ensure test coverage in the CI pipeline.
Closes #216
=> Add support for arm-linux

lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.2.4
=> bump upstream to 3.2.4

lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.2.6
=> dep: upgrade upstream to v3.2.6

lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.2.7
=> dep: update tailwindcss to v3.2.7

CHANGELOG.md, lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.3.1
=> dep: update tailwindcss to v3.3.1

CHANGELOG.md, lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.3.2
=> dep: update tailwindcss to v3.3.2

CHANGELOG.md, lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.3.6
=> dep: update tailwindcss to 3.3.6

CHANGELOG.md, lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.0
=> dep: update tailwindcss to v3.4.0

CHANGELOG.md, lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.1
=> dep: update tailwindcss to v3.4.1

README.md, Rakefile
- add table of contents
- new troubleshooting section on docker/tty
- add "commands" synopsis
- clarify language in a few sections
=> doc: improve README

test/integration/user_journey_test.sh
See https://github.com/net-ssh/bcrypt_pbkdf-ruby/issues/24
=> dep: work around bcrypt_pbkdf issue on windows

Gemfile.lock
Update Gemfile.lock with latest dependencies
=> dep: bundle update

lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.4
=> dep: update packaged tailwindcss to 3.4.4

lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.6
=> dep: update packaged tailwindcss to v3.4.6

lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.8
=> dep: update packaged tailwindcss to v3.4.8

CHANGELOG.md, lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.10
=> dep: update vendored tailwindcss to v3.4.10

lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.11
=> dep: update tailwindcss to v3.4.11

lib/tailwindcss/upstream.rb
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.13
=> dep: bump tailwindcss to 3.4.13

Gemfile.lock
to address https://github.com/rails/tailwindcss-rails/security/dependabot/53
=> dep: update webrick to 1.8.2

lib/generators/tailwindcss/scaffold/templates/_form.html.erb.tt
=> Fix naming regarding Rails form naming

README.md
For reference: 
- https://tailwindcss.com/docs/installation/using-postcss
- https://tailwindcss.com/docs/upgrade-guide#using-postcss
=> Update README for postcss configuration for v4

README.md
Just to update the link to the fingerprinting section in Asset Pipeline Guides.
=> Update Readme link for fingerprinting
